### ISSUE TITLE
Releasing new version, or move from tilde to carrot

### ISSUE THREAD

**Issue by oroce** [sandeepmistry/noble-device#11]
Noble 1.1.0 is out, but the latest release of noble-device's noble dependency is `~1.0.0` which wont allow installing `noble@1.1.0`.

ps: I'm really looking for this because as I was testing my four device (2 [sensortag](https://github.com/sandeepmistry/node-sensortag), 1 [flower-power](https://github.com/sandeepmistry/node-flower-power) and 1 [minew minibeacon](https://www.npmjs.com/package/minew-minibeacon)) setup and I found `noble@1.1.0` way more stable.

**Comment by sandeepmistry** [comment]
@oroce it's on my list :) Aiming to get something done by end of the week ...

Thanks for the feedback on the noble 1.1.0 release, I wanted to make sure things were settled before updating ``noble-device``

**Comment by oroce** [comment]
oh great, that's sounds amazing.

**Comment by sandeepmistry** [comment]
Done, version 1.1.0 has been published to npm.

I'll update node-sensortag and node-flower-power shortly ...

**Comment by oroce** [comment]
Thank you very much
