### ISSUE TITLE
es6 class inheritance

### ISSUE THREAD

**Issue by maxnowack** [sandeepmistry/noble-device#23]
It would be great if noble-device can be used with es6 features such as classes and promises

**Comment by sandeepmistry** [comment]
Hi @maxnowack,

Do you think this would be a breaking change, and force users to upgrade to a newer Node.js version?

Feel free to submit a PR with a proposal to get the discussion started ...

**Comment by maxnowack** [comment]
I don't think that this will be a breaking change. Basically we have to move the prototype changes from the `inherit` util directly to the NobleDevice prototype.
Is there a reason why the changes are currently done in this way?

**Comment by maxnowack** [comment]
Ah, these are static, not prototype methods. I'll submit a PR ;)

**Comment by sandeepmistry** [comment]
Closing this for now, please open a PR to continue the discussion.
