### ISSUE TITLE
Issue with connectAndSetup

### ISSUE THREAD

**Issue by larseen** [sandeepmistry/noble-device#26]
Seems to be some typos in the Readme, the code snippet:

```
YourThing.prototype.connectAndSetup = function(callback) {
  NobleDevice.prototype.connectAndSetup.call(this, function(error) {
    // maybe notify on a characteristic ?
    this.notifyCharacteristic(YOUR_THING_SERVICE_UUID, YOUR_THING_NOTIFY_CHAR, true, this._onRead.bind(this), function(err) {
      callback(err);
    });
  }.bind(this);
};
```

Does not work properly, also `connectAndSetup`/`connectAndSetUp`  have to spellings, is this intentional or just another typo?

**Comment by sandeepmistry** [comment]
Hey @larseen,

Thanks for bringing up the inconsistency, both `connectAndSetup` and `connectAndSetUp` are valid, but `connectAndSetUp` is preferred so I've updated the read me in https://github.com/sandeepmistry/noble-device/commit/f094b93dd299e52f62f53da993c1be96336ed24b for consistency.
